### ISSUE TITLE
Wrong version of release?

### ISSUE THREAD

**Issue by taooceros** [jjw24/WoxDictionary#6]
Hmmm have you released the wrong version of build? The detailed search are supposed to appear before synonym appears, because I used the IResultUpdate interface, however, in my computer, it appears at the same time (sometimes slow), which is not as intended as when I tested it.

**Comment by jjw24** [comment]
dont think so, but i have released again 2.1.0 try now

**Comment by taooceros** [comment]
Oh I think it is due to the merge issue here....https://github.com/Flow-Launcher/Flow.Launcher/pull/195
Thank you, and sorry for bothering😵
